spring:
  config:
    import:
      - optional:file:../.env[.properties]
      - optional:file:.env[.properties]
  application:
    name: flight-search
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 18084
external:
  flight-search:
    url: ${FLIGHT_SEARCH_PROVIDER_URL}