spring:
  config:
    import:
      - optional:file:../.env[.properties]
      - optional:file:.env[.properties]
  application:
    name: userprofile
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never

server:
  port: 18081

external:
  trips:
    url: ${TRIP_SERVICE_URL}
  expenses:
    url: ${EXPENSE_SERVICE_URL}

security:
  ignored: /**
  basic:
    enabled: false
management:
  security:
    enabled: false

jwt:
  key: ${JWT_KEY}
  expire: ${JWT_EXPIRE}