spring:
  config:
    import:
      - optional:file:../.env[.properties]
      - optional:file:.env[.properties]
  application:
    name: travelaggregator
  datasource:
    url: ${DB_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  mvc:
    log-request-details: true
server:
  port: ${SERVER_PORT}

external:
  trip:
    url: ${TRIP_SERVICE_URL}
jwt:
  key: ${JWT_KEY}
  expire: ${JWT_EXPIRE}
