spring:
  config:
    import: 
      - optional:file:../.env[.properties]
      - optional:file:.env[.properties]
  application:
    name: carhire-search
  jackson:
    property-naming-strategy: SNAKE_CASE
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
server:
  port: 18100
external:
  carhire-search:
    provider-url: ${CARHIRE_SEARCH_PROVIDER_URL}