spring:
  config:
    import:
      - optional:file:../.env[.properties]
      - optional:file:.env[.properties]
  application:
    name: experience-search
  jackson:
    property-naming-strategy: SNAKE_CASE
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
server:
  port: 18102
external:
  experience-search:
    provider-url: ${EXPERIENCE_SEARCH_PROVIDER_URL}